### ISSUE TITLE
Does not work `torchaudio.transforms.MelSpectrogram`, no MKL

### ISSUE THREAD

**Issue by Ayagoz** [osai-ai/dokai#1]
I used docker pulled from ghcr.io/osai-ai/dokai:21.05-pytorch.

The following code gives an error:

```python -c 'import torchaudio; import torch;  a = torch.randn(2, 4663744); torchaudio.transforms.MelSpectrogram(44100)(a)'```

```
/usr/local/lib/python3.8/dist-packages/torchaudio-0.8.0a0+e4e171a-py3.8-linux-x86_64.egg/torchaudio/functional/functional.py:357: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (201) may be set too low.
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchaudio-0.8.0a0+e4e171a-py3.8-linux-x86_64.egg/torchaudio/transforms.py", line 480, in forward
    specgram = self.spectrogram(waveform)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchaudio-0.8.0a0+e4e171a-py3.8-linux-x86_64.egg/torchaudio/transforms.py", line 96, in forward
    return F.spectrogram(
  File "/usr/local/lib/python3.8/dist-packages/torchaudio-0.8.0a0+e4e171a-py3.8-linux-x86_64.egg/torchaudio/functional/functional.py", line 91, in spectrogram
    spec_f = torch.stft(
  File "/usr/local/lib/python3.8/dist-packages/torch/functional.py", line 580, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
RuntimeError: fft: ATen not compiled with MKL support
```

and this check `python -c 'import torch; a = torch.randn(10); print(a.to_mkldnn().layout)'` works correctly.

**Comment by lRomul** [comment]
PyTorch is not compiled with MKL, so the CPU version of torch.stft
 does not work. But GPU version should work, you can try: 
`python -c 'import torchaudio; import torch; a = torch.randn(2, 4663744).cuda(); torchaudio.transforms.MelSpectrogram(44100).cuda()(a)'`

I don't know if it makes a lot of sense to compile torch with MKL and if I can do it freely.

**Comment by Ayagoz** [comment]
That works! Thanks!
